[package]
name = "automaton-apprentice"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Learning module for automaton"
repository.workspace = true

[dependencies]
automaton-proto = { path = "../automaton-proto" }
automaton-memory = { path = "../automaton-memory" }
thiserror.workspace = true
